CHANGELOG.md
CMakeLists.txt
bench/CMakeLists.txt

Just to be nice to people trying to build the project who made the effort to read the main CMakeLists to find out what are its dependencies.

CMake: declare dependencies in the main list

---

CHANGELOG.md
CMakeLists.txt
bindings/python/CMakeLists.txt

Hi,
Currently, releases are not pushed with an archive containing the submodule, and the project won't configure without the submodule, so we can't package this project from the tagged releases.
Here is a simple workaround.
On a side note, we should push archives containing the submodule anyway. And a GPG signature would be nice too. There is a command in the jrl cmake module for this. I can help with that too if needed :)

CMake: fetch submodule if not available

---

CHANGELOG.md
examples/ur10_ballistic.py
examples/utils/solo.py

In Pinocchio 2.6.21 the attribute is called [`parent`](https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/structpinocchio_1_1FrameTpl.html#a2aa4d066ee651eb8fd77bd2ae066ad92).

Fix name of frame parent attribute in examples

---

CHANGELOG.md
CMakeLists.txt

Export definitions in CMake config file.
This allow to use template instantiation in consumer project by linking against `aligator::aligator`.
The exports are:
- ALIGATOR_ENABLE_TEMPLATE_INSTANTIATION
- ALIGATOR_MULTITHREADING
- ALIGATOR_WITH_PINOCCHIO
- ALIGATOR_WITH_CROCODDYL_COMPAT

Export definition in CMake config file

---

CHANGELOG.md
doc/Doxyfile.extra.in
examples/se2-car.cpp

This PR:
* finishes the se2-car.cpp example
* fixes the Doxyfile's python directory

Finish implementing C++ se2-car.cpp example

---

bindings/python/src/expose-filter.cpp

This commit adds the possibility to access filter pairs in Python.

Fix access to filter pairs in Python

---

CHANGELOG.md
examples/CMakeLists.txt
examples/talos-arm.cpp

The relevant code is not that useful; this should fix the conda-forge recipe [build error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=864628&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823)
@jorisv @olivier-roussel

Remove cnpy dependency for example-talos-arm

---

CHANGELOG.md
tests/python/test_continous_dynamics.py
tests/python/utils.py

This PR aims at solving issue https://github.com/Simple-Robotics/aligator/issues/127#issue-2131916127 about an error in the finite difference python function used in unittest. It also adds some missing unittest for MultibodyFreeFwdDynamics derivatives.

Fix dynamics unittests involving finite difference function

---

CHANGELOG.md
bindings/python/src/modelling/expose-center-of-mass.cpp
bindings/python/src/modelling/expose-centroidal.cpp
bindings/python/src/modelling/expose-continuous-dynamics.cpp
bindings/python/src/modelling/expose-kinodynamics.cpp
examples/centroidal.py
examples/continuous-centroidal.py
examples/solo_kinodynamics.py
include/aligator/modelling/centroidal/angular-acceleration.hpp
include/aligator/modelling/centroidal/angular-acceleration.hxx
include/aligator/modelling/centroidal/centroidal-acceleration.hpp
include/aligator/modelling/centroidal/centroidal-acceleration.hxx
include/aligator/modelling/centroidal/wrench-cone.hpp
include/aligator/modelling/centroidal/wrench-cone.hxx
include/aligator/modelling/centroidal/wrench-cone.txx
include/aligator/modelling/dynamics/centroidal-fwd.hpp
include/aligator/modelling/dynamics/centroidal-fwd.hxx
include/aligator/modelling/dynamics/continuous-centroidal-fwd.hpp
include/aligator/modelling/dynamics/continuous-centroidal-fwd.hxx
include/aligator/modelling/dynamics/kinodynamics-fwd.hpp
include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
include/aligator/modelling/multibody/centroidal-momentum-derivative.hpp
include/aligator/modelling/multibody/centroidal-momentum-derivative.hxx
src/modelling/centroidal/wrench-cone.cpp
tests/python/test_centroidal.py
tests/python/test_continous_dynamics.py
tests/python/test_kinodynamics.py

This PR aims at adding a new feature to the centroidal dynamics and costs formulation, namely the option to consider 6D contacts with angular forces. It also provides an approximated wrench cone residual with 4 facets. The 6D contact dynamics is especially useful for robots with large feet like Talos.

Add 6D contact option to centroidal dynamics

---

CHANGELOG.md
CMakeLists.txt
src/compat/crocoddyl/CMakeLists.txt
tests/python/CMakeLists.txt

+ libraries/archives go to lib/
+ runtimes go to bin/
Same thing as what was done on proxsuite-nlp

Standardize CMake output directories

---

CHANGELOG.md
bindings/python/src/modelling/expose-center-of-mass.cpp
bindings/python/src/modelling/expose-force-cost.cpp
bindings/python/src/modelling/expose-pinocchio-functions.cpp
examples/solo_kinodynamics.py
include/aligator/modelling/dynamics/kinodynamics-fwd.hpp
include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
include/aligator/modelling/multibody/centroidal-momentum-derivative.hpp
include/aligator/modelling/multibody/centroidal-momentum-derivative.hxx
include/aligator/modelling/multibody/centroidal-momentum.hpp
include/aligator/modelling/multibody/centroidal-momentum.hxx
include/aligator/modelling/multibody/centroidal-momentum.txx
include/aligator/modelling/multibody/contact-force.hpp
include/aligator/modelling/multibody/contact-force.hxx
include/aligator/modelling/multibody/contact-force.txx
include/aligator/modelling/multibody/multibody-wrench-cone.hpp
include/aligator/modelling/multibody/multibody-wrench-cone.hxx
include/aligator/modelling/multibody/multibody-wrench-cone.txx
src/modelling/multibody/centroidal-momentum.cpp
src/modelling/multibody/contact-force.cpp
src/modelling/multibody/multibody-wrench-cone.cpp
tests/forces.cpp
tests/python/test_kinodynamics.py

This PR adds force and wrench cone costs for the multibody case. For now the costs recompute the constrained dynamics of the contact although it is already done in multibodyConstrainedDynamics. In the future the common data update will fix this redundant computation.

Add contact force and wrench cone costs for multibodies

---

CHANGELOG.md
gar/include/aligator/gar/blk-matrix.hpp
gar/include/aligator/gar/dense-riccati.hpp
gar/include/aligator/gar/dense-riccati.hxx

An undefined behavior cause test-cpp-gar-riccat to fail on MacOS + clang 18.
By initializing internal RiccatiSolverDense data structure  to zero, the problem is fixed.

Fix RiccatiSolverDense initialization

---

CHANGELOG.md
CMakeLists.txt

CMake 3.30 don't package anymore the FindBoost.cmake file. Instead, it encourage to use the BoostModule.cmake distributed by Boost.
To avoid a warning message, we must set the CMP0167 policy to NEW.
CMP0167 deprecate FetchContent_populate.

Set policy CMP0167 and CMP0169 to avoid warnings with CMake 3.30

---

CHANGELOG.md
include/aligator/solvers/fddp/solver-fddp.hxx
include/aligator/solvers/proxddp/solver-proxddp.hxx

The change avoids requirement a copy-assignment operator exists (and avoids a call to said operator to initialize the members).

[solvers] use placement-new for creating worksapce and results structs

---

.github/workflows/macos-linux-conda.yml
CHANGELOG.md
include/aligator/fwd.hpp
include/aligator/modelling/centroidal/angular-acceleration.hpp
include/aligator/modelling/centroidal/angular-momentum.hpp
include/aligator/modelling/centroidal/centroidal-acceleration.hpp
include/aligator/modelling/centroidal/centroidal-translation.hpp
include/aligator/modelling/centroidal/centroidal-wrapper.hpp
include/aligator/modelling/centroidal/friction-cone.hpp
include/aligator/modelling/centroidal/linear-momentum.hpp
include/aligator/modelling/centroidal/wrench-cone.hpp
include/aligator/modelling/dynamics/centroidal-fwd.hxx
include/aligator/modelling/dynamics/continuous-centroidal-fwd.hxx
include/aligator/modelling/dynamics/kinodynamics-fwd.hxx
include/aligator/modelling/dynamics/multibody-constraint-fwd.hxx
include/aligator/modelling/dynamics/multibody-free-fwd.hxx
include/aligator/modelling/multibody/center-of-mass-translation.hpp
include/aligator/modelling/multibody/center-of-mass-velocity.hpp
include/aligator/modelling/multibody/centroidal-momentum-derivative.hpp
include/aligator/modelling/multibody/centroidal-momentum.hpp
include/aligator/modelling/multibody/contact-force.hpp
include/aligator/modelling/multibody/fly-high.hpp
include/aligator/modelling/multibody/frame-placement.hpp
include/aligator/modelling/multibody/frame-translation.hpp
include/aligator/modelling/multibody/frame-velocity.hpp
include/aligator/modelling/multibody/multibody-wrench-cone.hpp

`aligator` now requires C++17, hence there is no longer any use for the `Eigen::aligned_allocator<T>` template class. Hence all aliases for the relevant std::vector type and use of std::allocate_shared (which takes an allocator type as argument) are useless.
This PR deprecates both the typedef for `std::vector<T, Eigen::aligned_allocator<T>>` and the `aligator::allocate_shared_eigen_aligned` function template, and removes all use of the later (replaced by vanilla `make_shared`).

[fwd.hpp] add deprecations for uses of Eigen::aligned_allocator

---

CHANGELOG.md
include/aligator/modelling/costs/log-residual-cost.hpp
include/aligator/modelling/costs/quad-residual-cost.hpp
tests/continuous.cpp
tests/costs.cpp

The function template `QuadraticResidualCost::getResidual<T>()` will attempt a cast to pointer-type `T*` or `const T*` to the expected actual type of the stored residual function.

[modelling/costs] Add getResidual() templated getter for composite cost functions

---

include/aligator/modelling/dynamics/kinodynamics-fwd.hpp

This PR fixes the include of LU from Eigen in the kynodynamics file which was breaking compilation.

Fixing include of LU from Eigen

---

.github/workflows/macos-linux-conda.yml
CHANGELOG.md
bindings/python/src/modelling/expose-cost-stack.cpp
examples/talos-walk-utils.cpp
include/aligator/modelling/costs/sum-of-costs.hpp
include/aligator/modelling/costs/sum-of-costs.hxx
src/modelling/costs/sum-of-costs.cpp
tests/costs.cpp
tests/python/test_costs.py

- Also adds a template getter for the component cost functions
- `addCost()` now has an overload taking a key (either a `std::size_t` or a string)
- `addCost()` returns a reference to the pair of cost function component and weight
Resolves #195

[modelling] Change CostStack backend to an unordered_map type

---

CHANGELOG.md
bindings/python/src/expose-solver-prox.cpp
include/aligator/context.hpp
include/aligator/fwd.hpp
include/aligator/solvers/proxddp/solver-proxddp.hpp
include/aligator/solvers/proxddp/solver-proxddp.hxx

We remove use of proxsuite-nlp's `BCLParams` struct and instead add an inner struct `AlmParams` to `SolverProxDDP`. This allows us to move some aligator-specific parameters inside of this struct.

Re-define ALM params struct internally to `aligator`

---

CHANGELOG.md
bench/croc-talos-arm.cpp
bench/lqr.cpp
bench/talos-walk.cpp
bindings/python/src/expose-solver-prox.cpp
examples/cartpole.py
examples/centroidal.py
examples/continuous-centroidal.py
examples/croc_arm_manipulation.py
examples/linear_euler.py
examples/lqr.py
examples/solo_kinodynamics.py
examples/talos-arm.cpp
examples/talos-walk.cpp
examples/talos_arms.py
examples/talos_walk.py
examples/ur5_croco.py
examples/ur5_reach.py
include/aligator/solvers/proxddp/solver-proxddp.hpp
include/aligator/solvers/proxddp/solver-proxddp.hxx
tests/python/test_constrained_dynamics.py
tests/python/test_example_problem.py
tests/python/test_solver.py

This PR removes the `rho_` parameter of the solver, which used to be the primal proximal regularization parameter but was not used anymore for a while. This is an **API BREAKING** change.

SolverProxDDP: remove solver parameter `rho_`

---

CHANGELOG.md
gar/include/aligator/gar/dense-riccati.hpp
gar/include/aligator/gar/dense-riccati.hxx
gar/include/aligator/gar/parallel-solver.hpp
gar/include/aligator/gar/parallel-solver.hxx
gar/include/aligator/gar/proximal-riccati.hpp
gar/include/aligator/gar/proximal-riccati.hxx
gar/include/aligator/gar/riccati-base.hpp
include/aligator/solvers/proxddp/solver-proxddp.hxx
tests/CMakeLists.txt
tests/cycling.cpp

This PR aims at adding a function to efficiently cycle the three different kind of linear solvers so as to avoid full reallocation at each MPC control cycle. Discussions are open to decide what is the best way to achieve it.

Cycle the Riccati solver

---

CHANGELOG.md
CMakeLists.txt
bindings/python/include/aligator/python/macros.hpp
gar/include/aligator/gar/lqr-problem.hpp
gar/include/aligator/gar/lqr-problem.hxx
gar/include/aligator/gar/utils.hpp
include/aligator/core/stage-data.hxx
include/aligator/core/stage-model.hxx
include/aligator/core/traj-opt-problem.hxx
include/aligator/fwd.hpp
include/aligator/math.hpp
include/aligator/modelling/costs/log-residual-cost.hxx
include/aligator/modelling/costs/quad-costs.hpp
include/aligator/solvers/fddp/solver-fddp.hxx
include/aligator/solvers/proxddp/solver-proxddp.hxx
include/aligator/utils/exceptions.hpp
include/aligator/utils/logger.hpp
include/aligator/utils/rollout.hpp
src/utils/exceptions.cpp
src/utils/logger.cpp

This PR makes changes to the `ALIGATOR_RUNTIME_ERROR` and `ALIGATOR_WARNING` macros, and cuts down on the number of LOC pulled into the header `aligator/utils/exceptions.hpp` which is included everywhere.
- add `src/utils/exceptions.cpp` which implements type-erased formatting function (following [this suggestion in fmtlib's docs](https://fmt.dev/latest/api/#type-erasure))
Merge after #229

Change formatting of exceptions, using variadic macro and type-erased implementation

---

CHANGELOG.md
examples/clqr.cpp
include/aligator/context.hpp
include/aligator/core/constraint.hpp
include/aligator/core/stage-model.hpp
include/aligator/core/traj-opt-problem.hpp
include/aligator/fwd.hpp
include/aligator/solvers/proxddp/solver-proxddp.hpp
include/aligator/solvers/proxddp/workspace.hpp

This follows changes and deprecations in [the latest proxsuite-nlp release](https://github.com/Simple-Robotics/proxsuite-nlp/releases/tag/v0.9.0).

Change from deprecated `ConstraintSetBase<T>` to `ConstraintSetTpl<T>`

---

CHANGELOG.md
bindings/python/src/modelling/expose-gravity-compensation.cpp
bindings/python/src/modelling/expose-pinocchio-functions.cpp
include/aligator/modelling/multibody/gravity-compensation-residual.hpp
include/aligator/modelling/multibody/gravity-compensation-residual.hxx
include/aligator/modelling/multibody/multibody-wrench-cone.hpp
src/modelling/multibody/gravity-compensation-residual.cpp
tests/python/test_gravity_compensation.py

This pull request adds a new StageFunction template class `GravityCompensationResidualTpl`, which models the function
$$ r(x, u) = Bu - \mathcal{G}(q) $$
where $G(q)$ is the generalized gravity, computed from Pinocchio.

Add gravity compensation residual

---

CHANGELOG.md
include/aligator/core/lagrangian.hpp
include/aligator/solvers/proxddp/solver-proxddp.hpp
include/aligator/solvers/proxddp/solver-proxddp.hxx

This PR implements a bunch of changes to ProxDDP.
+ lagrangian.hpp : move def out-of-line
+ [solvers/proxddp] have computeMultipliers() return a bool flag
+ [solvers/proxddp] add tmp vectors for linear search
+ [solvers/proxddp] Fix 'else' branch of BCL
+ [solvers/proxddp] move impl of setNumThreads to .hxx
The fix for the 'else' branch of BCL is **critical** and fixes a mistake introduced here: https://github.com/Simple-Robotics/aligator/blame/ae8d331b8db0a7dc53308ad47abf96a7be53b53f/include/aligator/solvers/proxddp/solver-proxddp.hxx#L511-L513 by https://github.com/Simple-Robotics/aligator/commit/755ca6507759dcdc7c723aaa447a9a2408861929

Fixes to ProxDDP

---

README.md

Since aligator doesn't build without pinocchio for now (https://github.com/Simple-Robotics/aligator/issues/241), this PR change build instruction to build with pinocchio support.

Fix build instruction

---

.gersemirc
.pre-commit-config.yaml
CMakeLists.txt
bindings/python/CMakeLists.txt
examples/CMakeLists.txt
tests/CMakeLists.txt
tests/python/CMakeLists.txt

This PR adds the cmake submodule directory to the set of definitions for gersemi formatting - this makes the formatter respect the case and properly format args.
This follows a discussion here: BlankSpruce/gersemi#44

[cmake] Add `cmake` submodule dir to gersemi definitions

---

.gersemirc
CMakeLists.txt
bench/CMakeLists.txt
examples/CMakeLists.txt
src/compat/crocoddyl/CMakeLists.txt
tests/CMakeLists.txt

[cmake] add a comment
[cmake] scoped target compile definitions
[cmake] tests: slight tweak to message printing target name and cpp file
gersemi: add bench/ dir
[cmake] Use cmake_parse_arguments() some more
create_ex_or_bench:
- add keyword arg BENCHMARK
- add multivalue arg DEPENDENCIES
- message: print filename between parentheses
Remove CMake macros:
- target_add_example_robot_data
- target_add_talos_walk
(directly add targets example-robot-data and talos_walk_utils
examples/CMakeLists.txt : do not use list EXAMPLES_LIST anymore
- create_example() : move message print to create_ex_or_bench call
- do not link talos-arm.cpp to example_robot_data explicitly -- croc_talos_arm_utils already had it

[cmake] Rework how translation units (examples/benchmarks) defined using cmake_parse_arguments()

---

CHANGELOG.md
CMakeLists.txt

The CMake pinocchio::pinocchio target link against all pinocchio sublibrary.
Aligator only need pinocchio_default (standard algorithms build with double) and pinocchio_parsers in one example.
Drawback : this fix doesn't support Pinocchio 2.

Don't link against all pinocchio

---

CHANGELOG.md
README.md
include/aligator/core/traj-opt-problem.hpp
include/aligator/core/traj-opt-problem.hxx
tests/problem.cpp

Hi,
When I tried to run the solo12 scenario from https://gitlab.laas.fr/gepetto/quadruped-reactive-walking, I got crashes from aligator.
I identified the following bug : the pointer `init_state_error_` in `TrajOptProblemTpl` was not updated across copy/move, which could result in wrong values or crashes.
I tried to make `TrajOptProblemTpl` non copyable nor movable, but I couldn't find a fix that would not break the python binding.
So I went for the obvious fix. Please let me know if you prefer another solution.

Fix copy of TrajOptProblem

---

CHANGELOG.md
src/utils/logger.cpp

Prevent duplication of log columns.
Duplication becomes problematic with multiple runs, e.g. in MPC.

Prevent duplication of log columns.

---

CHANGELOG.md
doc/Doxyfile.extra.in
include/aligator/core/solver-util.hpp
include/aligator/core/traj-opt-problem.hpp
include/aligator/core/traj-opt-problem.hxx
include/aligator/core/workspace-base.hpp
include/aligator/solvers/fddp/results.hpp
include/aligator/solvers/fddp/solver-fddp.hxx
include/aligator/solvers/proxddp/results.hxx
include/aligator/solvers/proxddp/solver-proxddp.hxx
include/aligator/solvers/proxddp/workspace.hxx
tests/problem.cpp

By default, if TrajOptProblem is given an initial state, the initial solution is initialized with this initial state for the first element, and with the neutral state for the others. Both these states can have very different values, yielding poor starting values for xs, prev_xs and trial_xs. In the classical case where all the states are in the same stage space, one might want to start with a constant solution. Instead of trying to detect if this is a desirable behavior, or adding a configuration parameter, an initialization callback is added to the problem, which can be set by the user before calling the solver setup(). If it is not set, the previous default behavior applies.

Allow customization of the initial solution.

---

CHANGELOG.md
examples/pendulum.py
examples/ur5_table_halfspace.py

Now with solver as input and `al_index` instead of `al_iters`.

Fix `HistoryCallback` initialization in examples

---

.github/workflows/macos-linux-pixi.yml
CITATION.cff
CITATIONS.bib

- **Update CITATIONS**
- **Add team member to CITATION.cff**
This PR updates the published IEEE T-RO paper, adds the RSS24 and @edantec 's Humanoids 2024 paper.
It also adds @edantec to the CITATION.cff file.

Update CITATIONS.bib and CITATION.cff

---

.github/workflows/macos-linux-pixi.yml

Only run workflow on push for `main` and `devel` branches.

macos-linux-pixi workflow: change branch rules

---

CHANGELOG.md
bindings/python/src/modelling/expose-pinocchio-functions.cpp
include/aligator/modelling/multibody/frame-collision.hpp
include/aligator/modelling/multibody/frame-collision.hxx
include/aligator/utils/exceptions.hpp
tests/python/test_frames.py

https://github.com/Simple-Robotics/aligator/issues/289#issuecomment-2832014757
Resolves #289.
When `FrameCollisionResidual` is initialized with a geometry that has no collision pairs, we get a segfault.

Fix segfault in `FrameCollisionResidual`, add corresponding test in `test_frames.py`

---

bindings/python/include/aligator/python/blk-matrix.hpp

[python] make BlkMatrixPythonVisitor an incomplete type when template argument is wrong

---

CHANGELOG.md
CMakeLists.txt
bench/CMakeLists.txt
bindings/python/src/expose-pinocchio-features.cpp
bindings/python/src/modelling/expose-constraintfwd.cpp
bindings/python/src/modelling/expose-force-cost.cpp
bindings/python/src/modelling/expose-pinocchio-functions.cpp
examples/CMakeLists.txt
include/aligator/modelling/multibody/contact-force.hpp
include/aligator/modelling/multibody/contact-force.hxx
include/aligator/modelling/multibody/context.hpp
include/aligator/modelling/multibody/multibody-friction-cone.hpp
include/aligator/modelling/multibody/multibody-friction-cone.hxx
include/aligator/modelling/multibody/multibody-wrench-cone.hpp
include/aligator/modelling/multibody/multibody-wrench-cone.hxx
pixi.lock
pixi.toml
src/modelling/dynamics/multibody-constraint-fwd.cpp
src/modelling/multibody/constrained-rnea.cpp
src/modelling/multibody/contact-force.cpp
src/modelling/multibody/multibody-friction-cone.cpp
src/modelling/multibody/multibody-wrench-cone.cpp
tests/CMakeLists.txt
tests/forces.cpp
tests/python/CMakeLists.txt

This pull request addresses the comments in discussion https://github.com/Simple-Robotics/aligator/discussions/303, and will officially remove support for Pinocchio 2 from aligator.
This will simplify the current checks for Pinocchio 3 in the library, since it is now the assumed minimum.
These will be superseded later on with checks for Pinocchio 4 when it releases.
Furthermore, we now assume that proxsuite-nlp was built with Pinocchio support -- which was already a required check in CMake.

Officially remove support for Pinocchio 2, require Pinocchio >= 3.4

---

CHANGELOG.md
bindings/python/include/aligator/python/visitors.hpp
bindings/python/src/expose-solver-prox.cpp
include/aligator/solvers/proxddp/results.hpp

In Python, users can now do
```python
res_copy = res.copy()
res_copy = copy.copy(res)
```
Resolves #321

solvers : make proxddp algo's `Results` class copyable again (in C++ and Python)
